model:
  img_in_channels: 1024
  hidden_dim: 512
  num_heads: 8
  num_layers: 2
  mlp_ratio: 3.5
  image_grid_size: 10
  text_max_length: 32
  fusion_token_num: 16
  dropout: 0.1
  freeze_bert: true
  precomputed_bert_path: /home/soic/Desktop/LightDet/units/model/cards/cache/bert_raw_cache.pt